name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests and save results
      run: |
        pytest --maxfail=1 --disable-warnings --tb=short > results.txt || true

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results.txt
